server:
  port: 9001
spring:
  application:
    name: cards
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: qa
  config:
    import:
      optionals:
        - "application-${spring.profiles.active}.yml"


build:
  version: "3.0"

cards:
  message: "Welcome to PeopleBank cards related local APIs "
  contactDetails:
    name: "Know Program Lech - Developer"
    email: "dragos@peoplebank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932