spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          # enabled: true
          # disable default url
          enabled: false
          # add the below property to accept service name only with lowercase letters
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  # add gateway endpoint
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: gatewayserver
    version: 1.0.0
    description: PeopleBank Gateway Server Application

logging:
  level:
    com.peoplebank.gatewayserver: debug

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000