spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          # enabled: true
          # disable default url
          enabled: false
          # add the below property to accept service name only with lowercase letters
          lowerCaseServiceId: true
      httpclient:
        connection-timeout: 1000 # Time to establish connection (in ms)
        response-timeout: 2s # Max time to wait for a response
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  # add gateway endpoint
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: gatewayserver
    version: 1.0.0
    description: PeopleBank Gateway Server Application

logging:
  level:
    com.peoplebank.gatewayserver: debug

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000