server:
  port: 8080
spring:
  application:
    name: accounts
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: prod
  config:
    import:
      - "application-${spring.profiles.active}.yml"

build:
  version: "3.0"

accounts:
  message: "Accounts Microservice - Local"
  contactDetails:
    name: "Accounts Microservice - Developer"
    email: "0V7ZD@example.com"
  onCallSupport:
    - (555) 555-5555
    - (555) 555-5556